### ISSUE TITLE
Class 'Site' not found

### ISSUE THREAD

**Issue by damarw** [Regulus343/Identify#7]
Class 'Site' not found when register new user

**Comment by Regulus343** [comment]
Thanks for the report, I see the email views reference "Site" even though the alias will not necessarily be set. You can either set the alias in the `aliases` array of `app/config/app.php`, or update your views in `resources/views/vendor/identify/emails` to replace `Site` with `Regulus\SolidSite\Facade`. This will be fixed in the next update and then I'll close this issue.
